/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Address: typeof import('@/types')['Address']
  const Asset: typeof import('@/types')['Asset']
  const AssetStatusEnum: typeof import('./src/types/assets')['AssetStatusEnum']
  const EffectScope: typeof import('vue')['EffectScope']
  const GenerateAssetTagPayload: typeof import('@/types')['GenerateAssetTagPayload']
  const Packaging: typeof import('@/types')['Packaging']
  const PaginatedResponse: typeof import('@/types')['PaginatedResponse']
  const Product: typeof import('@/types')['Product']
  const ProductVariety: typeof import('@/types')['ProductVariety']
  const PurchaseOrderStatusEnum: typeof import('./src/types/purchase_order')['PurchaseOrderStatusEnum']
  const StatesEnum: typeof import('./src/types/common')['StatesEnum']
  const StatusEnum: typeof import('./src/types/assets')['StatusEnum']
  const Supplier: typeof import('@/types')['Supplier']
  const UnitEnum: typeof import('./src/types/common')['UnitEnum']
  const [alias]: typeof import('[package-name]')['[from]']
  const [import-names]: typeof import('[package-name]')['[import-names]'] 
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const axios: typeof import('axios')['default']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const effectScope: typeof import('vue')['effectScope']
  const get: typeof import('zod')['get']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const set: typeof import('zod')['set']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAssetStore: typeof import('./src/stores/assets')['useAssetStore']
  const useAttrs: typeof import('vue')['useAttrs']
  const useCartStore: typeof import('./src/stores/supplier')['useCartStore']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useForm: typeof import('vee-validate')['useForm']
  const useLink: typeof import('vue-router')['useLink']
  const useMyFetch: typeof import('@vueuse/core')['useFetch']
  const usePageStore: typeof import('./src/stores/page')['usePageStore']
  const useProductStore: typeof import('./src/stores/product')['useProductStore']
  const useProductVarietyStore: typeof import('./src/stores/productVariety')['useProductVarietyStore']
  const usePurchaseOrderStore: typeof import('./src/stores/purchase_order')['usePurchaseOrderStore']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSlots: typeof import('vue')['useSlots']
  const useSupplierStore: typeof import('./src/stores/supplier')['useSupplierStore']
  const vee-useForm: typeof import('vee-validate')['vee-useForm']
  const vee-validate: typeof import('vee-validate')['vee-validate']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const z: typeof import('zod')['z']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Supplier, Address, PaginatedResponse, Product, Packaging, Asset, GenerateAssetTagPayload, ProductVariety, PurchaseOrder, PurchaseOrderItem } from '@/types'
  import('@/types')
  // @ts-ignore
  export type { AssetStatusEnum } from './src/types/assets'
  import('./src/types/assets')
  // @ts-ignore
  export type { UnitEnum, StatesEnum } from './src/types/common'
  import('./src/types/common')
  // @ts-ignore
  export type { PurchaseOrderStatusEnum } from './src/types/purchase_order'
  import('./src/types/purchase_order')
}
